-- CreateTable
CREATE TABLE "reportes_malla" (
    "id" TEXT NOT NULL,
    "proyecto_id" TEXT NOT NULL,
    "codigo" TEXT NOT NULL,
    "version" TEXT NOT NULL DEFAULT '00',
    "fecha_doc" TEXT NOT NULL DEFAULT '',
    "especialista" TEXT,
    "contratista" TEXT,
    "entidad" TEXT,
    "ubicacion" TEXT,
    "estructura" TEXT,
    "fecha" TEXT,
    "n_registro" TEXT,
    "plano_referencial" TEXT,
    "nivel_corona" TEXT,
    "nivel_pie_talud" TEXT,
    "n_columnas_malla" TEXT,
    "malla_tipo" TEXT,
    "malla_marca" TEXT,
    "malla_abertura" TEXT,
    "malla_diametro_alambre" TEXT,
    "malla_tipo_union" TEXT,
    "malla_norma" TEXT,
    "alambre_material" TEXT,
    "alambre_diametro" TEXT,
    "alambre_tension_rotura" TEXT,
    "grapas_material" TEXT,
    "grapas_diametro" TEXT,
    "grapas_tuercas" TEXT,
    "inst_fecha" TEXT,
    "inst_ancho_rollo" TEXT,
    "inst_altura_rollo_fab" TEXT,
    "inst_long_prot_ini" TEXT,
    "inst_altura_prot_ini" TEXT,
    "inst_long_prot_fin" TEXT,
    "inst_altura_prot_fin" TEXT,
    "inst_area_protegida" TEXT,
    "inst_uso_grapas" TEXT,
    "representante_sr" TEXT,
    "representante_contratista" TEXT,
    "logo_sr_path" TEXT,
    "logo_cliente_path" TEXT,
    "foto_registro_path" TEXT,
    "elevacion_path" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reportes_malla_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "reportes_malla" ADD CONSTRAINT "reportes_malla_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "proyectos"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
